name: smartcitizen-data
channels:
  - conda-forge
  - defaults
dependencies:
  - colorama
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - joblib
  - json5
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_contrib_core
  - jupyter_core
  - jupyter_nbextensions_configurator
  - jupyterlab
  - jupyterlab_server
  - keras
  - keras-applications
  - keras-base
  - keras-preprocessing
  - markdown
  - markupsafe
  - matplotlib
  - numpy
  - pandas
  - pickleshare
  - pip
  - plotly
  - python=3.7.*
  - python-dateutil
  - pyyaml
  - requests
  - ruamel_yaml
  - scikit-learn
  - scipy
  - seaborn
  - shapely
  - statsmodels
  - tensorboard
  - tensorflow
  - tensorflow-base
  - tensorflow-estimator
  - urllib3
  - werkzeug
  - wheel
  - widgetsnbextension
  - xlsxwriter
  - yaml
  - pip:
    - tabulate
    - pdfrw
    - reportlab
    - termcolor
    - tzwhere
